const swaggerAutogen = require("swagger-autogen")();

const doc = {
    info: {
        version: "1.0.0",
        title: "typescript test",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:5000",
    basePath: "/",
    schemas: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "User",
            "description": "Endpoints"
        }
    ],
    securityDefinitions: {
        Bearer:{
            type: "apiKey",
            in: "header",       // can be "header", "query" or "cookie"
            name: "Bearer",  // name of the header, query parameter or cookie
        }
    },
    definitions: {

    }
};

const outputFile = './src/swagger-output.json';
const endpointsFiles = ["./src/app.ts"];

swaggerAutogen(outputFile, endpointsFiles, doc).then(async () => {

});