const swaggerAutogen = require("swagger-autogen")();

const doc = {
    info: {
        version: "1.0.0",
        title: "Hanghae Eats",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "3.36.97.199",
    basePath: "/",
    schemas: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "User",
            "description": "Endpoints"
        }
    ],
    securityDefinitions: {
        Bearer: {
        type: "apiKey",
        name: "Authorization",
        in: "header",
        description: "Enter your bearer token in the format **Bearer &lt;token>**"
        }
    },
    security: [
        {
        Bearer: []
        }
    ],
    definitions: {

    }
};

const outputFile = './src/swagger-output.json';
const endpointsFiles = ["./src/app.ts"];

swaggerAutogen(outputFile, endpointsFiles, doc).then(async () => {

});